### ISSUE TITLE
Error with Qgis 2.8 Wien

### ISSUE THREAD

**Issue by glorenzetto** [nextgis/MultiQML#4] opened 2015-03-04 09:17 UTC
Hi, 
   i try to use the plugin, but when i start i get this error:
Errore durante l'esecuzione di codice Python:

NotImplementedError: QgsPluginLayer.writeSymbology() is abstract and must be overridden

Versione Python:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

Versione di QGIS:
2.8.1-Wien Wien, exported

have you any ideas to solve this problem?
bye

**Comment by glorenzetto** [comment] 2015-03-04 09:42
I've a new about my problem...after the message i report previously, the plugin starts correcly and work good with vector layers.
But if i try to use it with my rasters (creating by a my organization's software), i get this new error:
Errore durante l'esecuzione di codice Python:


Traceback (most recent call last):
  File "C:/Documents and Settings/glorenzetto/.qgis2/python/plugins\multiqml\multiqml.py", line 98, in on_pbnApplyStyle_clicked
    self.myPluginMessage( QCoreApplication.translate("MultiQmlDlg", "Unable to apply vector qml style \"%1\" to raster layer \"%2\".")\
AttributeError: 'unicode' object has no attribute 'arg'


Versione Python:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]


Versione di QGIS:
2.8.1-Wien Wien, exported

bye

**Comment by kylesomerville** [comment] 2015-06-05 14:37
Similar experience here when using QGIS 2.8 Wien (for multiple rasters)

An error has occured while executing Python code:


Traceback (most recent call last):
  File "C:/Users/Owner/.qgis2/python/plugins\multiqml\multiqml.py", line 98, in on_pbnApplyStyle_clicked
    self.myPluginMessage( QCoreApplication.translate("MultiQmlDlg", "Unable to apply vector qml style \"%1\" to raster layer \"%2\".")\
AttributeError: 'unicode' object has no attribute 'arg'


Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]


QGIS version:
2.8.1-Wien Wien, exported

Python path: ['C:/Users/Owner/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python', u'C:/Users/Owner/.qgis2/python', u'C:/Users/Owner/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'c:\\progra~1\\qgiswi~1\\apps\\python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'c:\\progra~1\\qgiswi~1\\apps\\python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'c:\\progra~1\\qgiswi~1\\apps\\python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'c:\\progra~1\\qgiswi~1\\apps\\python27\\lib\\site-packages\\shapely-1.2.18-py2.7-win-amd64.egg', 'c:\\progra~1\\qgiswi~1\\apps\\python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'c:\\progra~1\\qgiswi~1\\apps\\python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'c:\\progra~1\\qgiswi~1\\apps\\python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'C:/Users/Owner/.qgis2//python', 'C:\\Users\\Owner\\.qgis2\\python\\plugins\\FeatureGridCreator', '.', 'C:\\Users\\Owner\\.qgis2\\python\\plugins\\QuickMultiAttributeEdit/forms', 'C

**Comment by agentili** [comment] 2015-06-10 16:34
I guys,

I got the same problem and I fixed it with the below line 

Before [line 97]:
        elif ( layer.type() == QgsMapLayer.RasterLayer ) and not isRasterQml():
After [line97]
        elif ( layer.type() == QgsMapLayer.RasterLayer ) and isRasterQml():

From my side the problem is solved
Please let us know if is the same for you

Thanks

**Comment by simgislab** [comment] 2015-06-10 16:40
can you send a pull-request?

**Comment by fejikso** [comment] 2015-06-29 18:33
@agentili , your fix worked for me. Thanks!

**Comment by kylesomerville** [comment] 2015-07-01 08:33
@agentili apologies, am not a programmer and a complete noob - which file do I add these lines to?

**Comment by agentili** [comment] 2015-07-01 09:50
@fejikso @kylesomerville 
Sorry guys.. looking to the code I raise a pull-request but seems not accepted yet.

Anyway forget to what I wrote above (later i will change it) and do what I suggest in the pull-request.
You can find it here (https://github.com/nextgis/MultiQML/pull/5/files#diff-50c192f9c924a713117df7d6983af5e0)

**Comment by simgislab** [comment] 2015-07-01 16:19
will check and merge it soon, sorry for the delay!

**Comment by simgislab** [comment] 2015-08-05 21:52
pull request merged, thanks

**Closed by simgislab** 2015-08-05 21:52 UTC
